import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { JSDOM } from 'jsdom';
import { createElement } from 'react';
import { MockProvider } from '@firelaunch/agent';
import { televisionFromSpec } from '@firelaunch/tv';
import { createApi } from '../../server/src/api.js';
import { ProjectRepository } from '../../server/src/repository.js';
import App from '../src/App.js';

const dom = new JSDOM('<!doctype html><html><body></body></html>', { url: 'http://127.0.0.1:4173/' });
Object.assign(globalThis, { window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement });
Object.defineProperty(globalThis, 'navigator', { configurable: true, value: dom.window.navigator });
const { cleanup, fireEvent, render, screen, waitFor } = await import('@testing-library/react');

test('Studio golden path creates, edits, refines, generates, blocks build, hands off and reloads', async () => {
  const directory = await mkdtemp(path.join(tmpdir(), 'firelaunch-studio-'));
  const server = createApi(new ProjectRepository(directory), new MockProvider());
  let activeServer = server;
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
  const address = server.address();
  assert.ok(address && typeof address !== 'string');
  const nativeFetch = globalThis.fetch;
  globalThis.fetch = ((input: RequestInfo | URL, init?: RequestInit) => nativeFetch(new URL(String(input), `http://127.0.0.1:${address.port}`), init)) as typeof fetch;
  try {
    render(createElement(App));
    fireEvent.change(await screen.findByPlaceholderText('e.g. Wild Earth'), { target: { value: 'My Channel' } });
    fireEvent.click(screen.getByRole('button', { name: /Continue/ }));
    fireEvent.click(screen.getByRole('button', { name: /Create channel/ }));
    await waitFor(() => assert.ok(screen.getAllByRole('button', { name: 'Open Field Notes' }).length), { timeout: 5000 });
    await waitFor(() => assert.ok(screen.getByText('REV 8 · LOCAL')), { timeout: 5000 });
    const projectId = new URLSearchParams(window.location.search).get('project');
    assert.match(projectId ?? '', /^ch_[a-f0-9]{32}$/);
    fireEvent.click(screen.getByRole('button', { name: /Design/ }));
    fireEvent.change(screen.getByLabelText(/PRIMARY/), { target: { value: '#aabbcc' } });
    fireEvent.click(screen.getByRole('button', { name: /Save brand/ }));
    await waitFor(() => assert.ok(screen.getByText('REV 9 · LOCAL')));
    fireEvent.click(screen.getByRole('button', { name: /Content/ }));
    fireEvent.click(screen.getByRole('button', { name: 'Field Notes' }));
    fireEvent.change(screen.getByLabelText('DESCRIPTION'), { target: { value: 'Edited in Studio' } });
    fireEvent.click(screen.getByRole('button', { name: 'Save film' }));
    await waitFor(() => assert.ok(screen.getByText('REV 10 · LOCAL')));
    fireEvent.click(screen.getByRole('button', { name: /Create/ }));
    await screen.findByText(/MOCK · Deterministic mock/);
    fireEvent.change(screen.getByPlaceholderText('e.g. Add page Explore'), { target: { value: 'primary color to #224466' } });
    fireEvent.click(screen.getByRole('button', { name: /Send request/ }));
    await waitFor(() => assert.ok(screen.getByText('REV 11 · LOCAL')));
    fireEvent.click(screen.getByRole('button', { name: /Code/ }));
    await waitFor(() => assert.equal((screen.getByRole('button', { name: 'Generate source' }) as HTMLButtonElement).disabled, false));
    fireEvent.click(screen.getByRole('button', { name: 'Generate source' }));
    await waitFor(() => assert.ok(screen.getByRole('button', { name: 'src/channel.json' })));
    const generated = JSON.parse((await nativeFetch(`http://127.0.0.1:${address.port}/api/projects/${projectId}/code/file?path=src%2Fchannel.json`).then(response => response.json())).content);
    const current = await nativeFetch(`http://127.0.0.1:${address.port}/api/projects/${projectId}`).then(response => response.json());
    assert.deepEqual(generated, televisionFromSpec(current.spec));
    fireEvent.click(screen.getByRole('button', { name: /Build/ }));
    fireEvent.click(await screen.findByRole('button', { name: 'Run Vega release build' }));
    await waitFor(() => assert.ok(screen.getByText(/VEGA_SDK_PATH not set/)));
    fireEvent.click(screen.getByRole('button', { name: /Publish/ }));
    await screen.findByText('Submission handoff');
    await waitFor(() => assert.equal((screen.getByRole('button', { name: 'Create local submission bundle' }) as HTMLButtonElement).disabled, false));
    fireEvent.click(screen.getByRole('button', { name: 'Create local submission bundle' }));
    await waitFor(() => assert.ok(screen.getByText(/not submitted/)));
    cleanup();
    render(createElement(App));
    await waitFor(() => assert.ok(screen.getAllByRole('button', { name: 'Open Field Notes' }).length));
    await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve()));
    const restarted = createApi(new ProjectRepository(directory), new MockProvider());
    restarted.listen(address.port, '127.0.0.1');
    await new Promise<void>(resolve => restarted.once('listening', resolve));
    activeServer = restarted;
    const response = await nativeFetch(`http://127.0.0.1:${address.port}/api/projects/${projectId}`);
    const saved = await response.json();
    assert.equal(saved.revision, 11);
    assert.equal(saved.spec.brand.primaryColor, '#224466');
    assert.equal(saved.spec.content[0].description, 'Edited in Studio');
    assert.deepEqual(generated, televisionFromSpec(saved.spec));
    assert.equal((await nativeFetch(`http://127.0.0.1:${address.port}/api/projects/${projectId}/readiness`).then(result => result.json())).submitted, false);
  } finally {
    cleanup(); globalThis.fetch = nativeFetch;
    if (activeServer.listening) await new Promise<void>((resolve, reject) => activeServer.close(error => error ? reject(error) : resolve()));
    await rm(directory, { recursive: true, force: true });
  }
});
